ES_FrontEnd/Controllers/CustomerController.cs
using ES_FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using System.Net;

namespace ES_FrontEnd.Controllers
{
    public class CustomerController : Controller
    {
        private static HttpClient _httpClient;

        #region configuration
        public CustomerController(IConfiguration configuration)
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new System.Uri(configuration["ApiBaseUrl"]);
        }
        #endregion

        #region getCustomer
        [HttpGet]
        public async Task<JsonResult> getCustomer()
        {
            int? id = CommonVariable.UserId();
            HttpResponseMessage res = null;
            res = await _httpClient.GetAsync($"Customer/GetByUserId/{id}");
            if (res != null && res.IsSuccessStatusCode)
            {
                var data = await res.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<CustomerModel>(data);
                return Json(result);
            }
            else
            {
                var data = await res.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<dynamic>(data);
                return Json(new { message = Convert.ToString(result.message) });
            }
        }
        #endregion

        #region SaveCustomer
        [HttpPost]
        public async Task<JsonResult> SaveCustomerAsync(CustomerModel customer)
        {
            if (customer.CustomerId == null)
            {
                HttpResponseMessage res = null;
                try
                {
                    var json = JsonConvert.SerializeObject(customer);
                    var content = new StringContent(json, Encoding.UTF8, "application/json");
                    res = await _httpClient.PostAsync("Customer/PostCustomer", content);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                }
                if (res != null && res.IsSuccessStatusCode)
                {
                    var data = await res.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<dynamic>(data);
                    return Json(new {message = Convert.ToString(result.message)});
                }
                else if(res != null && res.StatusCode == HttpStatusCode.BadRequest)
                {
                    var data = await res.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<dynamic>(data);
                    Console.WriteLine(result);
                    return Json(new { message = "Please Fill All Field in the Form" });
                }
                else
                {
                    var data = await res.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<dynamic>(data);
                    return Json(new { message = Convert.ToString(result.message) });
                }
            }
            else
            {
                HttpResponseMessage res = null;
                try
                {
                    var json = JsonConvert.SerializeObject(customer);
                    var content = new StringContent(json, Encoding.UTF8, "application/json");
                    res = await _httpClient.PutAsync($"Customer/PutCustomer/{customer.CustomerId}", content);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
                if (res != null && res.IsSuccessStatusCode)
                {
                    var data = await res.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<dynamic>(data);
                    return Json(new { message = Convert.ToString(result.message) });
                }
                else if (res != null && res.StatusCode == HttpStatusCode.BadRequest)
                {
                    var data = await res.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<dynamic>(data);
                    Console.WriteLine(result);
                    return Json(new { message = "Please Fill All Field in the Form" });
                }
                else
                {
                    var data = await res.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<dynamic>(data);
                    TempData["message"] = result.message;
                    return Json(new { message = Convert.ToString(result.message) });
                }
            }
        }
        #endregion
    }
}

ES_FrontEnd/Controllers/OrderController.cs
using ES_FrontEnd.Areas.Admin.Controllers;
using ES_FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ES_FrontEnd.Controllers
{
    [CheckAccess]
    public class OrderController : Controller
    {
        private HttpClient _httpClient;

        #region configuration
        public OrderController(IConfiguration configuration)
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new System.Uri(configuration["ApiBaseUrl"]);
        }
        #endregion

        #region GetOrderbyUserid
        public async Task<List<OrderModel>> GetOrderbyUserId()
        {
            List<OrderModel> data = new List<OrderModel>();
            int? id = CommonVariable.UserId();
            HttpResponseMessage res = null;
            try
            {
                res = await _httpClient.GetAsync($"Order/GetByUserId/{id}");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                data = JsonConvert.DeserializeObject<List<OrderModel>>(content);
            }
            return data;
        }
        #endregion

        #region ViewPage
        public async Task<IActionResult> Index()
        {
            List<OrderModel> orders = new List<OrderModel>();
            orders = await GetOrderbyUserId();
            foreach(var data in orders)
            {
                Console.WriteLine(data.OrderId);
            }
            ViewBag.Orders = orders;
            return View("OrderPage");
        }
        #endregion

        #region checkout
        [HttpPost]
        [Route("/Checkout")]
        public async Task<IActionResult> Checkout(IFormCollection fc)
        {
            HttpResponseMessage res = null;
            try
            {
                res = await _httpClient.GetAsync($"Product/GetById/{fc["id"]}");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<ProductModel>(content);
                ViewBag.Product = data;
                TempData["Quantity"] = fc["Quantity"];
                int discount = 0;
                TempData["Discount"] = discount;
            }
            return View("Checkout");
        }
        #endregion

        [HttpPost]
        public async Task<IActionResult> SaveOrder(OrderModel model,IFormCollection fc)
        {
            HttpResponseMessage res = null;
            bool flag = false;
            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            try
            {
                res = await _httpClient.PostAsync($"Order/PostOrder",content);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                List<OrderModel> values = new List<OrderModel>();
                values  = await GetOrderbyUserId();
                OrderDetailsModel odm = new OrderDetailsModel
                {
                    ProductId = Convert.ToInt32(fc["ProductId"]),
                    OrderId = values[0].OrderId ?? 0,
                    Quantity = Convert.ToInt32(fc["Quantity"]),
                    Amount = model.Price,
                    TotalAmount = (model.Price * Convert.ToInt32(fc["Quantity"])),
                    UserId = model.UserId
                }; 
                OrderDetailsController od1 = new OrderDetailsController(_httpClient);
                flag = await od1.SaveOrderDetails(odm);
                if(flag == true)
                {
                    return View("OrderSuccess");
                }
                return View("Checkout");
            }
            else
            {
                TempData["message"] = "Sorry Your Order Can't be Taken";
                return View("Checkout");
            }
        }
        public IActionResult OrderSuccess()
        {
            return View();
        }
    }
}

ES_FrontEnd/Controllers/ProductController.cs
using ES_FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace ES_FrontEnd.Controllers
{
    [CheckAccess]
    public class ProductController : Controller
    {
        private HttpClient _httpClient;

        #region configuration
        public ProductController(IConfiguration configuration)
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new System.Uri(configuration["ApiBaseUrl"]);
        }
        #endregion

        #region ProductList
        [HttpPost]
        public async Task<IActionResult> Index(SearchProductModel model)
        {
            HttpResponseMessage res = null;
            try
            {
                var json = JsonConvert.SerializeObject(model);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                res = await _httpClient.PostAsync("Product/SearchProduct",content);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<List<ProductModel>>(content);
                ViewBag.Products = data;
                return View("ProductPage");
            }
            else
            {
                var content = await res.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<dynamic>(content);
                TempData["message"] = data.message;
                Console.WriteLine(data.message);
                return View("ProductPage");
            }
        }
        #endregion

        #region ProductSingle
        public async Task<IActionResult> ProductSingle(int id)
        {
            HttpResponseMessage res = null;
            try
            {
                res = await _httpClient.GetAsync($"Product/GetById/{id}");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<ProductModel>(content);
                ViewBag.Product = data;
                return View("ProductSingle");
            }
            else
            {
                var content = await res.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<dynamic>(content);
                TempData["message"] = data.message;
                return View("ProductSingle");
            }
        }
        #endregion
    }
}

ES_FrontEnd/Views/Shared/_ACview.cshtml
<div class="row mb-3">
    <label for="inputEmail" class="col-sm-2 col-form-label">Capacity</label>
    <div class="col-sm-10">
        <select class="form-control form-select form-control-a" name="Capacity">
            <option>Select Capacity</option>
            <option value="1">1 Ton</option>
            <option value="1.1">1.1 Ton</option>
            <option value="1.3">1.3 Ton</option>
            <option value="1.5">1.5 Ton</option>
            <option value="1.6">1.6 Ton</option>
            <option value="1.8">1.8 Ton</option>
            <option value="1.95">1.95 Ton</option>
            <option value="2.2">2.2 Ton</option>
            <option value="2.5">2.5 Ton</option>
            <option value="3">3 Ton</option>
        </select>
    </div>
</div>

<div class="row mb-3">
    <label for="inputEmail" class="col-sm-2 col-form-label">Refrigerant</label>
    <div class="col-sm-10">
        <select class="form-control form-select form-control-a" name="Refrigerant">
            <option>Select Refrigerant</option>
            <option value="R32">R32</option>
            <option value="R410">R410</option>
        </select>
    </div>
</div>

<div class="row mb-3">
    <label for="inputEmail" class="col-sm-2 col-form-label">Voltage</label>
    <div class="col-sm-10">
        <select class="form-control form-select form-control-a" name="Voltage">
            <option>Select Voltage</option>
            <option value="220">220</option>
            <option value="etc">etc</option>
        </select>
    </div>
</div>

<div class="row mb-3">
    <label for="inputEmail" class="col-sm-2 col-form-label">Color</label>
    <div class="col-sm-10">
        <select class="form-control form-select form-control-a" name="Color">
            <option>Select Color</option>
            <option value="White">White</option>
            <option value="Black">Black</option>
            <option value="Grey">Grey</option>
            <option value="Silver">Silver</option>
        </select>
    </div>
</div>

ES_FrontEnd/Views/Shared/_Layout_Admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Darshil Refrigeration Admin</title>
    <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
          name="viewport" />
    <link href="~/img/Darshil-Refrigeration.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Fonts and icons -->
    <script src="~/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
          google: { families: ["Public Sans:300,400,500,600,700"] },
          custom: {
            families: [
              "Font Awesome 5 Solid",
              "Font Awesome 5 Regular",
              "Font Awesome 5 Brands",
              "simple-line-icons",
            ],
            urls: ["~/css/fonts.min.css"],
          },
          active: function () {
            sessionStorage.fonts = true;
          },
        });
    </script>

    <!-- CSS Files -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/plugins.min.css" />
    <link rel="stylesheet" href="~/css/kaiadmin.min.css" />

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="~/css/demo.css" />
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar -->
        <div class="sidebar" data-background-color="dark">
            <div class="sidebar-logo">
                <!-- Logo Header -->
                <div class="logo-header" data-background-color="dark">
                    <img src="~/img/Darshil-Refrigeration.png"
                         alt="navbar brand"
                         class="navbar-brand logo" />
                    <div class="nav-toggle">
                        <button class="btn btn-toggle toggle-sidebar">
                            <i class="gg-menu-right"></i>
                        </button>
                        <button class="btn btn-toggle sidenav-toggler">
                            <i class="gg-menu-left"></i>
                        </button>
                    </div>
                    <button class="topbar-toggler more">
                        <i class="gg-more-vertical-alt"></i>
                    </button>
                </div>
                <!-- End Logo Header -->
            </div>
            <div class="sidebar-wrapper scrollbar scrollbar-inner">
                <div class="sidebar-content">
                    <ul class="nav nav-secondary">
                        <li class="nav-item active">
                            <a class="collapsed" aria-expanded="false" asp-area="Admin" asp-controller="Home" asp-action="Index">
                                <p>Dashboard</p>
                            </a>
                        </li>
                        <li class="nav-section">
                            <h4 class="text-section">Tables</h4>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="User" asp-action="Index">
                                <p>Users</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Customer" asp-action="Index">
                                <p>Customer</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Index">
                                <p>Product</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Order" asp-action="Index">
                                <p>Order</p>
                            </a>
                        </li>
                        <li class="nav-section">
                            <h4 class="text-section">Add New Data</h4>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="User" asp-action="Insert">
                                <p>Users</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Customer" asp-action="Insert">
                                <p>Customer</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Insert">
                                <p>Product</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- End Sidebar -->

        <div class="main-panel">
            <div class="main-header">
                <div class="main-header-logo">
                </div>
                <!-- Navbar Header -->
                <nav class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom">
                    <div class="container-fluid">
                        <nav class="navbar navbar-header-left navbar-expand-lg navbar-form nav-search p-0 d-none d-lg-flex">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <button type="submit" class="btn btn-search pe-1">
                                        <i class="fa fa-search search-icon"></i>
                                    </button>
                                </div>
                                <input type="text"
                                       placeholder="Search ..."
                                       class="form-control" />
                            </div>
                        </nav>

                        <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
                            <li class="nav-item topbar-icon dropdown hidden-caret d-flex d-lg-none">
                                <a class="nav-link dropdown-toggle"
                                   data-bs-toggle="dropdown"
                                   href="#"
                                   role="button"
                                   aria-expanded="false"
                                   aria-haspopup="true">
                                    <i class="fa fa-search"></i>
                                </a>
                                <div class="dropdown-menu dropdown-search animated fadeIn">
                                    <form class="navbar-left navbar-form nav-search">
                                        <div class="input-group">
                                            <input type="text"
                                                   placeholder="Search ..."
                                                   class="form-control" />
                                        </div>
                                    </form>
                                </div>
                            </li>

                            <li class="nav-item topbar-user dropdown hidden-caret">
                                <a class="dropdown-toggle profile-pic"
                                   data-bs-toggle="dropdown"
                                   href="#"
                                   aria-expanded="false">
                                    <span class="profile-username">
                                        <span class="op-7">Hi,</span>
                                        <span class="fw-bold">@CommonVariable.UserName()</span>
                                    </span>
                                </a>
                                <div class="dropdown-menu dropdown-user animated fadeIn">
                                    <div class="dropdown-user-scroll scrollbar-outer">
                                        <div class="user-box">
                                            <div class="u-text">
                                                <h4>@CommonVariable.UserName()</h4>
                                                <p class="text-muted">@CommonVariable.Email()</p>
                                                <p class="text-muted">@CommonVariable.Role()</p>

                                                <a href="profile.html"
                                                   class="btn btn-xs btn-secondary btn-sm">View Profile</a>
                                            </div>
                                        </div>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">My Profile</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">Account Setting</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-controller="User" asp-action="Logout">Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
                <!-- End Navbar -->
            </div>

            <div class="container">
                <div class="page-inner">
                    @RenderBody()
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid d-flex justify-content-between">
                    <div class="copyright">
                        2025, made with by Darshil Refrigeration
                    </div>
                    <div>
                        Distributed by Darshil Refrigeration.
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <!--   Core JS Files   -->
    <script src="~/js/core/jquery-3.7.1.min.js"></script>
    <script src="~/js/core/popper.min.js"></script>
    <script src="~/js/core/bootstrap.min.js"></script>

    <!-- jQuery Scrollbar -->
    <script src="~/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>

    <!-- Chart JS -->
    <script src="~/js/plugin/chart.js/chart.min.js"></script>

    <!-- jQuery Sparkline -->
    <script src="~/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>

    <!-- Chart Circle -->
    <script src="~/js/plugin/chart-circle/circles.min.js"></script>

    <!-- Datatables -->
    <script src="~/js/plugin/datatables/datatables.min.js"></script>

    <!-- Bootstrap Notify -->
    <script src="~/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>

    <!-- jQuery Vector Maps -->
    <script src="~/js/plugin/jsvectormap/jsvectormap.min.js"></script>
    <script src="~/js/plugin/jsvectormap/world.js"></script>

    <!-- Sweet Alert -->
    <script src="~/js/plugin/sweetalert/sweetalert.min.js"></script>

    <!-- Kaiadmin JS -->
    <script src="~/js/kaiadmin.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ES_FrontEnd/Views/Shared/_Layout_Login.cshtml
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
          crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/loginstyle.css">
    <title>Darshil Refrigeration</title>
    <link href="~/img/Darshil-Refrigeration.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">
</head>
<body>
    @RenderBody()
    <script src="~/js/loginscript.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

ES_FrontEnd/Views/Shared/_TVview.cshtml
<div class="row mb-3">
    <label for="inputEmail" class="col-sm-2 col-form-label">Sizes</label>
    <div class="col-sm-10">
        <select class="form-control form-select form-control-a" name="Sizes">
            <option>Select TV inch</option>
            <option value="32">32 inch</option>
            <option value="40">40 inch</option>
            <option value="43">43 inch</option>
            <option value="55">55 inch</option>
            <option value="65">65 inch</option>
            <option value="75">75 inch</option>
            <option value="85">85 inch</option>
            <option value="98">98 inch</option>
        </select>
    </div>
</div>

<div class="row mb-3">
    <label for="inputEmail" class="col-sm-2 col-form-label">Resolution</label>
    <div class="col-sm-10">
        <select class="form-control form-select form-control-a" name="Resolution">
            <option>Select Resolution</option>
            <option value="HD">HD</option>
            <option value="FHD">FHD</option>
            <option value="2K">2K</option>
            <option value="QHD">QHD</option>
            <option value="UHD">UHD</option>
            <option value="4K">4K</option>
        </select>
    </div>
</div>

<div class="row mb-3">
    <label for="inputEmail" class="col-sm-2 col-form-label">HDTechnology</label>
    <div class="col-sm-10">
        <select class="form-control form-select form-control-a" name="HDTechnology">
            <option>Select HD Technology</option>
            <option value="HDR">HDR</option>
            <option value="HDR 10">HDR 10</option>
            <option value="HDR 1600">HDR 1600</option>
            <option value="QLED">QLED</option>
        </select>
    </div>
</div>

<div class="row mb-3">
    <label for="inputEmail" class="col-sm-2 col-form-label">RefreshRate</label>
    <div class="col-sm-10">
        <select class="form-control form-select form-control-a" name="RefreshRate">
            <option>Select Refresh Rate</option>
            <option value="60">60Hz</option>
            <option value="120">120Hz</option>
        </select>
    </div>
</div>

<div class="row mb-3">
    <label for="inputEmail" class="col-sm-2 col-form-label">SoundTechnology</label>
    <div class="col-sm-10">
        <select class="form-control form-select form-control-a" name="SoundTechnology">
            <option>Select Sound Technology</option>
            <option value="Dolby Audio">Dolby Audio</option>
            <option value="Dolby Atmos">Dolby Atmos</option>
            <option value="DTS X">DTS X</option>
        </select>
    </div>
</div>