ES_FrontEnd/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ES_FrontEnd.Areas.Admin.Models;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace ES_FrontEnd.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]/[action]")]
    [CheckAccess]
    public class OrderController : Controller
    {
        private HttpClient _httpClient;

        #region configuration
        public OrderController(IConfiguration configuration)
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new System.Uri(configuration["ApiBaseUrl"]);
        }
        #endregion

        #region GetAllOrder
        public async Task<IActionResult> Index()
        {
            HttpResponseMessage res = null;
            try
            {
                res = await _httpClient.GetAsync("Order/GetAllOrder");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<List<OrderModel>>(content);
                return View("OrderList", data);
            }
            else
            {
                var content = await res.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<dynamic>(content);
                TempData["message"] = data.message;
                return View("OrderList");
            }
        }
        #endregion

        #region DeleteOrder
        [HttpDelete("/DeleteOrder/{id}")]
        public async Task<JsonResult> DeleteOrder(int id)
        {
            HttpResponseMessage res = null;
            try
            {
                res = await _httpClient.DeleteAsync($"Order/DeleteOrder/{id}");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<dynamic>(content);
                return Json(new { message = Convert.ToString(result.message) });
            }
            else
            {
                var content = await res.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<dynamic>(content);
                return Json(new { message = Convert.ToString(result.message) });
            }
        }
        #endregion

        #region ViewOrder
        [HttpGet("{id}")]
        public async Task<IActionResult> ViewOrder(int id)
        {
            OrderDetailsController od = new OrderDetailsController(_httpClient);
            List<OrderDetailsModel> odm = new List<OrderDetailsModel>();
            odm = await od.GetAllOrderDetails(id);
            ViewBag.OrderDetail = odm;

            BillController bc = new BillController(_httpClient);
            List<BillModel> bm = new List<BillModel>();
            bm = await bc.GetAllBill(id);
            ViewBag.Bills = bm;
            return View("ViewOrder");
        }
        #endregion

        #region SaveBills
        [HttpPost]
        public async Task<IActionResult> SaveBills(BillModel Bill)
        {
            BillController bc = new BillController(_httpClient);
            if (await bc.Save(Bill))
            {
                return Json(new { message = "Bill Inserted" });
            }
            return Json(new { message = "Bill Not Inserted" });
        }
        #endregion
    }
}

ES_FrontEnd/Controllers/OrderController.cs
using ES_FrontEnd.Areas.Admin.Controllers;
using ES_FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ES_FrontEnd.Controllers
{
    [CheckAccess]
    public class OrderController : Controller
    {
        private HttpClient _httpClient;

        #region configuration
        public OrderController(IConfiguration configuration)
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new System.Uri(configuration["ApiBaseUrl"]);
        }
        #endregion

        #region GetOrderbyUserid
        public async Task<List<OrderModel>> GetOrderbyUserId()
        {
            List<OrderModel> data = new List<OrderModel>();
            int? id = CommonVariable.UserId();
            HttpResponseMessage res = null;
            try
            {
                res = await _httpClient.GetAsync($"Order/GetByUserId/{id}");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                data = JsonConvert.DeserializeObject<List<OrderModel>>(content);
            }
            return data;
        }
        #endregion

        #region ViewPage
        public async Task<IActionResult> Index()
        {
            List<OrderModel> orders = new List<OrderModel>();
            orders = await GetOrderbyUserId();
            foreach(var data in orders)
            {
                Console.WriteLine(data.OrderId);
            }
            ViewBag.Orders = orders;
            return View("OrderPage");
        }
        #endregion

        #region checkout
        [HttpPost]
        [Route("/Checkout")]
        public async Task<IActionResult> Checkout(IFormCollection fc)
        {
            HttpResponseMessage res = null;
            try
            {
                res = await _httpClient.GetAsync($"Product/GetById/{fc["id"]}");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<ProductModel>(content);
                ViewBag.Product = data;
                TempData["Quantity"] = fc["Quantity"];
                int discount = 0;
                TempData["Discount"] = discount;
            }
            return View("Checkout");
        }
        #endregion

        [HttpPost]
        public async Task<IActionResult> SaveOrder(OrderModel model,IFormCollection fc)
        {
            HttpResponseMessage res = null;
            bool flag = false;
            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            try
            {
                res = await _httpClient.PostAsync($"Order/PostOrder",content);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                List<OrderModel> values = new List<OrderModel>();
                values  = await GetOrderbyUserId();
                OrderDetailsModel odm = new OrderDetailsModel
                {
                    ProductId = Convert.ToInt32(fc["ProductId"]),
                    OrderId = values[0].OrderId ?? 0,
                    Quantity = Convert.ToInt32(fc["Quantity"]),
                    Amount = model.Price,
                    TotalAmount = (model.Price * Convert.ToInt32(fc["Quantity"])),
                    UserId = model.UserId
                }; 
                OrderDetailsController od1 = new OrderDetailsController(_httpClient);
                flag = await od1.SaveOrderDetails(odm);
                if(flag == true)
                {
                    return View("OrderSuccess");
                }
                return View("Checkout");
            }
            else
            {
                TempData["message"] = "Sorry Your Order Can't be Taken";
                return View("Checkout");
            }
        }
        public IActionResult OrderSuccess()
        {
            return View();
        }
    }
}

ES_FrontEnd/Controllers/OrderDetailsController.cs
using ES_FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;
using System.Text;

namespace ES_FrontEnd.Controllers
{
    [CheckAccess]
    public class OrderDetailsController : Controller
    {
        private HttpClient _httpClient;

        #region configuration
        public OrderDetailsController(HttpClient http)
        {
            _httpClient = http;
        }
        #endregion

        #region GetAllOrderDetails
        public async Task<IActionResult> Index()
        {
            HttpResponseMessage res = null;
            try
            {
                res = await _httpClient.GetAsync("OrderDetails/GetAllOrderDetails");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<List<OrderDetailsModel>>(content);
                return View("OrderDetailsList", data);
            }
            else
            {
                var content = await res.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<dynamic>(content);
                Console.WriteLine(data);
                TempData["message"] = data.message;
                return View("OrderDetailsList");
            }
        }
        #endregion

        #region DeleteOrderDetails
        [HttpDelete("/DeleteOrderDetails/{id}")]
        public async Task<JsonResult> DeleteOrderDetails(int id)
        {
            HttpResponseMessage res = null;
            try
            {
                res = await _httpClient.DeleteAsync($"OrderDetails/DeleteOrderDetails/{id}");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            if (res != null && res.IsSuccessStatusCode)
            {
                var content = await res.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<dynamic>(content);
                return Json(new { message = Convert.ToString(result.message) });
            }
            else
            {
                var content = await res.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<dynamic>(content);
                return Json(new { message = Convert.ToString(result.message) });
            }
        }
        #endregion

        #region Save
        [HttpPost]
        public async Task<bool> SaveOrderDetails(OrderDetailsModel OrderDetails)
        {
            HttpResponseMessage res;
            var json = JsonConvert.SerializeObject(OrderDetails);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            res = await _httpClient.PostAsync("OrderDetails/PostOrderDetails", content);
            if (res.IsSuccessStatusCode)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        #endregion
    }
}

ES_FrontEnd/Areas/Admin/Views/Order/Insert.cshtml
@using ES_FrontEnd.Areas.Admin.Models
@{
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model OrderModel
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Insert Bill</h5>

        <!-- General Form Elements -->
        <form asp-area="Admin" asp-controller="OrderDetails" asp-action="Save" method="post">
            <div class="row mb-3">
                <div class="col-sm-10">
                    <input type="hidden" class="form-control" asp-for="OrderId">
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputText" class="col-sm-2 col-form-label">Quantity</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="Price">
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputText" class="col-sm-2 col-form-label">Quantity</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="ShippingAddress">
                    <span asp-validation-for="ShippingAddress" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputText" class="col-sm-2 col-form-label">Amount </label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="PaymentMode">
                    <span asp-validation-for="PaymentMode" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputEmail" class="col-sm-2 col-form-label">Select User</label>
                <div class="col-sm-10">
                    <select id="UserId"
                            name="UserId"
                            class="form-select form-control"
                            asp-for="UserId">
                        <option value="">Select User</option>
                        @if (ViewBag.UserList != null)
                        {
                            @foreach (var user in ViewBag.UserList)
                            {
                                if (user.StateID == Model.UserId)
                                {
                                    <option value="@user.UserId">@user.UserName</option>
                                }
                                else
                                {
                                    <option value="@user.UserId">@user.UserName</option>
                                }
                            }
                        }
                    </select>
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Save Record</label>
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>

        </form><!-- End General Form Elements -->

    </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        console.log("load")
        $.ajax({
            url: "/UserDropDown",
            type: "GET",
            success: function (data) {
                console.log(data)
                $("#UserId")
                    .empty()
                    .append('<option value="">Select User</option>');
                $.each(data, function (i, user) {
                    $("#UserId").append(
                        '<option value="' +
                        user.userid +
                        '">' +
                        user.userName +
                        "</option>"
                    );
                });
                console.log(state.UserId);
            },
        });
    });
</script>

@if (TempData["message"] != null)
{
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(()=>{
            swal("@TempData["message"]", {
              buttons: {
                confirm: {
                  className: "btn btn-success",
                },
              },
            });
        })
    </script>
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ES_FrontEnd/Areas/Admin/Views/Order/OrderList.cshtml
@using ES_FrontEnd.Areas.Admin.Models
@{
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<OrderModel>
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="d-flex align-items-center">
                <h4 class="card-title">OrderList</h4>
            </div>
        </div>
        <div class="card-body">

            <div class="table-responsive">
            @if (Model != null)
            {
                <table id="add-row"
                       class="display table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>OrderId</th>
                                <th>Price</th>
                                <th>ShippingAddress</th>
                                <th>PaymentMode</th>
                                <th>OrderDate</th>
                                <th>UserName</th>
                                <th style="width: 10%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var data in Model)
                            {
                                <tr>
                                    <td>@data.OrderId</td>
                                    <td>@data.Price</td>
                                    <td>@data.ShippingAddress</td>
                                    <td>@data.PaymentMode</td>
                                    <td>@data.OrderDate</td>
                                    <td>@data.UserName</td>
                                    <td>
                                        <div class="form-button-action">
                                            <a asp-controller="Order" asp-area="Admin" asp-action="ViewOrder" asp-route-id="@data.OrderId">
                                                <button class="btn btn-info me-2">View</button>
                                            </a>
                                            <button class="btn btn-danger" id="Delete" onclick="confirmDelete(@data.OrderId)">Cancel</button>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                </table>
            }
            else
            {
                <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
                <script type="text/javascript">
                    $(document).ready(()=>{
                        swal("@TempData["message"]", {
                          buttons: {
                            confirm: {
                              className: "btn btn-success",
                            },
                          },
                        });
                    })
                </script>
            }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript">
    function confirmDelete(id){
      swal({
        title: "Are you sure?",
        text: "You won't be able to revert this!",
        type: "warning",
        buttons: {
            cancel: {
                visible: true,
                text: "No, cancel!",
                className: "btn btn-danger",
            },
            confirm: {
                text: "Yes, Cancel this Order!",
                className: "btn btn-success",
            },
        },
      }).then((willDelete) => {
        if (willDelete) {
          $.ajax({
              type:"DELETE",
              url:`/DeleteOrder/${id}`,
              success:function(data){
                swal(data.message, {
                icon: "success",
                buttons: {
                    confirm: {
                    className: "btn btn-success",
                    },
                },
              }).then((ok)=>{
                  if(ok){
                      window.location.reload();
                  }
              });
              }
          });
      } else {
        swal("Order is Safe", {
          buttons: {
            confirm: {
              className: "btn btn-success",
            },
          },
        });
        }
      });
    }
</script>
<link rel="stylesheet" href="~/css/plugins.min.css" />
<script src="~/js/plugin/sweetalert/sweetalert.min.js"></script>

ES_FrontEnd/Areas/Admin/Views/Order/ViewOrder.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
@using ES_FrontEnd;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <div class="card-title">OrderDetails Table</div>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">ProductName</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Amount</th>
                        <th scope="col">TotalAmount</th>
                        <th scope="col">UserName</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var od in ViewBag.OrderDetail)
                    {
                        <tr>
                            <td>@od.ProductName</td>
                            <td>@od.Quantity</td>
                            <td>@od.Amount</td>
                            <td>@od.TotalAmount</td>
                            <td>@od.UserName</td>
                        </tr>
                        <input type="hidden" id="Amount" value="@od.Amount" />
                        <input type="hidden" id="TotalAmount" value="@od.TotalAmount" />
                        <input type="hidden" id="OrderId" value="@od.OrderId" />
                        <input type="hidden" id="UserId" value="@CommonVariable.UserId()" />
                    }
                </tbody>
            </table>
        </div>
    </div>
    <button class="btn btn-primary mb-5" onclick="GenrateBill()">GenrateBill</button>
    <div class="card">
        <div class="card-header">
            <div class="card-title">Bills Table</div>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">BillNumber</th>
                        <th scope="col">BillDate</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Discount</th>
                        <th scope="col">TotalAmount</th>
                        <th scope="col">UserName</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var bd in ViewBag.Bills)
                    {
                        <tr>
                            <td>@bd.BillNumber</td>
                            <td>@bd.BillDate</td>
                            <td>@bd.Amount</td>
                            <td>@bd.Discount</td>
                            <td>@bd.TotalAmount</td>
                            <td>@bd.UserName</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript">
        function GenrateBill(){
            var id = $("#OrderId").val();
            console.log(id);
            console.log($("#Amount").val());
            console.log($("#TotalAmount").val());
            console.log($("#UserId").val());
            $.ajax({
                type: "POST",
                url: "/Admin/Order/SaveBills", // Updated to include area and controller
                data: {
                    "Amount": $("#Amount").val(),
                    "Discount": 1,
                    "TotalAmount": $("#TotalAmount").val(),
                    "OrderId": $("#OrderId").val(),
                    "UserId": $("#UserId").val()
                },
                success: function(data){
                    console.log(data);
                    window.location.reload();
                },
                error: function(xhr, status, error){
                    console.error("Error:", error);
                }
            });
        }
    </script>